mongodb:
  uri: "mongodb+srv://admin:4sZf4uIsrlO6GCoV@staging-cluster.olgilw6.mongodb.net/user_management"
  database: "job_management"
  collections:
    - projects
    - jobs

postgresql:
  host: "ss-stag-dev-db-paij5iezee.supersourcing.com"
  port: 5432
  database: "job_interaction_staging"
  user: "bluerangZbEbusr"
  password: "Year#2015eba"
  tables:
    - job_interactions
    - job_actions

json_dir: "data"